// ETag demo: We set long-lived response with ETag auto-generated by cache handler.
export async function GET() {
  const issuedAt = new Date();
  
  return Response.json({
    feature: "etag",
    issuedAt: issuedAt.toISOString(),
    now: new Date().toISOString(),
  }, {
    headers: {
      "Cache-Control": "public, max-age=60",
    }
  });
}